/* Localized report-window renderer with a copy-data fallback. */
(function (root) {
  "use strict";
  var q = root.QJZH = root.QJZH || {};
  var COPY = {
    zh: { title: "青境智衡环境报告", heading: "季度环境报告", watermark: "演示版・仅用于赛事展示", range: "统计范围", to: "至", empty: "所选范围内无记录", metric: "指标", result: "结果", compliance: "氨气达标率", ammonia: "平均/最高氨气", temperature: "温度范围", advice: "建议次数", risk: "风险分布", source: "数据来源", generated: "生成时间", print: "打印 / 另存 PDF", normal: "正常", watch: "关注", todo: "待办", urgent: "紧急", local: "QJZH 本地记录", institution: "机构模拟圈舍" },
    en: { title: "Qingjing Zhiheng Environment Report", heading: "Quarterly Environment Report", watermark: "DEMO · FOR COMPETITION PRESENTATION ONLY", range: "Date range", to: "to", empty: "No records in the selected range", metric: "Metric", result: "Result", compliance: "Ammonia compliance rate", ammonia: "Average / peak ammonia", temperature: "Temperature range", advice: "Recommendations", risk: "Risk distribution", source: "Data source", generated: "Generated", print: "Print / Save as PDF", normal: "Normal", watch: "Watch", todo: "To-do", urgent: "Urgent", local: "QJZH local records", institution: "Institution demo barns" },
    bo: { title: "མཐོ་སྒང་ཁོར་ཡུག་སྙན་ཞུ", heading: "དུས་ཚིགས་ཁོར་ཡུག་སྙན་ཞུ", watermark: "དཔེ་སྟོན་པར་གཞི · འགྲན་བསྡུར་འགྲེམས་སྟོན་ཁོ་ན", range: "བསྡོམས་རྩིས་དུས་ཡུན", to: "ནས", empty: "བདམས་པའི་ཁྱབ་ཁོངས་སུ་ཟིན་ཐོ་མེད", metric: "ཚད་གཞི", result: "འབྲས་བུ", compliance: "ཨམ་མོ་ནི་ཡ་ཚད་ལོངས་ཚད", ammonia: "ཆ་སྙོམས / མཐོ་ཤོས་ཨམ་མོ་ནི་ཡ", temperature: "དྲོད་ཚད་ཁྱབ་ཁོངས", advice: "བསམ་འཆར་གྲངས", risk: "ཉེན་ཁའི་ཁྱབ་ཚུལ", source: "གཞི་གྲངས་ཁུངས", generated: "བཟོས་པའི་དུས་ཚོད", print: "པར་འདེབས / PDF ཉར", normal: "རྒྱུན་ལྡན", watch: "དོ་སྣང", todo: "བྱ་དགོས", urgent: "ཛ་དྲག", local: "QJZH ས་གནས་ཟིན་ཐོ", institution: "སྒྲིག་འཛུགས་དཔེ་སྟོན་ཕྱུགས་ཁང" }
  };
  function esc(value) { return String(value == null ? "" : value).replace(/[&<>"']/g, function (character) { return { "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[character]; }); }
  function language(data) { var value = data && data.language || root.document && root.document.documentElement && root.document.documentElement.dataset.language || "zh"; return COPY[value] ? value : "zh"; }
  function sourceLabel(source, copy) { if (source === "QJZH 本地记录") return copy.local; if (source === "机构模拟圈舍") return copy.institution; return source; }
  function riskLabel(key, copy) { return { "正常": copy.normal, "关注": copy.watch, "待办": copy.todo, "紧急": copy.urgent }[key] || key; }
  function buildHtml(data) {
    var lang = language(data), copy = COPY[lang], distribution = data.riskDistribution || {};
    var table = data.noRecords ? "<p class='empty'>" + esc(copy.empty) + "</p>" : "<table><tr><th>" + esc(copy.metric) + "</th><th>" + esc(copy.result) + "</th></tr>" +
      "<tr><td>" + esc(copy.compliance) + "</td><td>" + (Number(data.complianceRate || 0) * 100).toFixed(1) + "%</td></tr>" +
      "<tr><td>" + esc(copy.ammonia) + "</td><td>" + Number(data.averageNh3 || 0).toFixed(1) + " / " + Number(data.maxNh3 || 0).toFixed(1) + " ppm</td></tr>" +
      "<tr><td>" + esc(copy.temperature) + "</td><td>" + (data.temperatureRange && data.temperatureRange.min != null ? esc(data.temperatureRange.min) + "–" + esc(data.temperatureRange.max) + " ℃" : "-") + "</td></tr>" +
      "<tr><td>" + esc(copy.advice) + "</td><td>" + esc(data.adviceCount || 0) + "</td></tr>" +
      "<tr><td>" + esc(copy.risk) + "</td><td>" + Object.keys(distribution).map(function (key) { return esc(riskLabel(key, copy)) + ": " + esc(distribution[key]); }).join(" · ") + "</td></tr></table>";
    return "<!doctype html><html lang='" + esc(lang === "zh" ? "zh-CN" : lang) + "'><head><meta charset='utf-8'><meta name='viewport' content='width=device-width,initial-scale=1'><title>" + esc(copy.title) + "</title><style>body{font:14px system-ui,-apple-system,sans-serif;color:#17232d;margin:15mm;line-height:1.6}.watermark{padding:8px 12px;border:1px solid #d6a93d;background:#fff7db;color:#7b5000;text-align:center;font-weight:700;letter-spacing:.06em}h1{color:#116b5a;margin:24px 0 8px}table{width:100%;border-collapse:collapse;margin:20px 0}td,th{border:1px solid #cbd5dc;padding:8px;text-align:left}th{background:#eef7f4}.meta{color:#566875}.empty{padding:24px;background:#f3f6f7}button{padding:9px 14px;border:0;border-radius:6px;background:#116b5a;color:#fff}@media print{button{display:none}}@page{size:A4;margin:15mm}</style></head><body><div class='watermark'>" + esc(copy.watermark) + "</div><h1>" + esc(copy.heading) + "</h1><p class='meta'>" + esc(copy.range) + "：" + esc(data.startDate) + " " + esc(copy.to) + " " + esc(data.endDate) + "</p>" + table + "<p class='meta'>" + esc(copy.source) + "：" + esc(sourceLabel(data.source, copy)) + " · " + esc(copy.generated) + "：" + esc(data.generatedAt) + "</p><button onclick='window.print()'>" + esc(copy.print) + "</button></body></html>";
  }
  function render(data) {
    var html = buildHtml(data);
    var reportWindow = root.open ? root.open("", "qjzh-report", "width=900,height=700") : null;
    if (reportWindow) { reportWindow.document.write(html); reportWindow.document.close(); reportWindow.focus(); root.setTimeout(function () { try { reportWindow.print(); } catch (_) {} }, 120); return reportWindow; }
    var text = JSON.stringify(data, null, 2);
    if (root.navigator && root.navigator.clipboard) root.navigator.clipboard.writeText(text);
    else if (root.document) { var area = root.document.createElement("textarea"); area.value = text; root.document.body.appendChild(area); area.select(); root.document.execCommand("copy"); area.remove(); }
    return null;
  }
  function renderInstitution(rows, selectedLanguage) { return render({ language: selectedLanguage || language(), startDate: "", endDate: "", noRecords: !rows.length, complianceRate: rows.filter(function (row) { return Number(row.calibrated_nh3_ppm) < 10; }).length / (rows.length || 1), averageNh3: rows.reduce(function (sum, row) { return sum + Number(row.calibrated_nh3_ppm || 0); }, 0) / (rows.length || 1), maxNh3: rows.reduce(function (max, row) { return Math.max(max, Number(row.calibrated_nh3_ppm || 0)); }, 0), temperatureRange: { min: null, max: null }, adviceCount: rows.filter(function (row) { return Number(row.calibrated_nh3_ppm) >= 10; }).length, riskDistribution: {}, generatedAt: new Date().toISOString(), source: "机构模拟圈舍" }); }
  q.reportRenderer = { COPY: COPY, buildHtml: buildHtml, render: render, renderInstitution: renderInstitution };
  root.addEventListener("DOMContentLoaded", function () { var button = root.document.getElementById("generateReport"); if (!button) return; button.addEventListener("click", function () { var lang = root.document.documentElement.dataset.language || "zh"; var data = q.reportGenerator.generate({ startDate: root.document.getElementById("reportStartDate") && root.document.getElementById("reportStartDate").value, endDate: root.document.getElementById("reportEndDate") && root.document.getElementById("reportEndDate").value, language: lang }); var status = root.document.getElementById("reportStatus"); if (status) { status.className = "qjzh-data-state qjzh-state-" + (data.noRecords ? "warning" : "empty"); status.textContent = data.noRecords ? COPY[lang].empty : (lang === "en" ? "Report generated. Opening the print window." : lang === "bo" ? "སྙན་ཞུ་བཟོས་ཟིན། པར་འདེབས་སྒེའུ་ཁུང་ཁ་ཕྱེ་བཞིན།" : "报告已生成，正在打开打印窗口。"); } render(data); }); });
})(window);
