/* Clean report window renderer with copy-data fallback. */
(function (root) {
  "use strict";
  var q = root.QJZH = root.QJZH || {};
  function esc(v) { return String(v == null ? "" : v).replace(/[&<>"]/g, function (c) { return { "&": "&amp;", "<": "&lt;", ">": "&gt;", "\"": "&quot;" }[c]; }); }
  function render(data) {
    var html = "<!doctype html><html><head><meta charset='utf-8'><title>青境智衡环境报告</title><style>body{font:14px Arial;color:#17232d;margin:15mm}h1{color:#116b5a}table{width:100%;border-collapse:collapse}td,th{border:1px solid #ccd;padding:7px;text-align:left}@media print{button{display:none}}@page{size:A4;margin:15mm}</style></head><body><h1>季度环境报告</h1><p>统计范围：" + esc(data.startDate) + " 至 " + esc(data.endDate) + "</p>" + (data.noRecords ? "<p>所选范围内无记录</p>" : "<table><tr><th>指标</th><th>结果</th></tr><tr><td>氨气达标率</td><td>" + (data.complianceRate * 100).toFixed(1) + "%</td></tr><tr><td>平均/最高氨气</td><td>" + data.averageNh3.toFixed(1) + " / " + data.maxNh3.toFixed(1) + " ppm</td></tr><tr><td>温度范围</td><td>" + (data.temperatureRange.min == null ? "-" : data.temperatureRange.min + "~" + data.temperatureRange.max + " ℃") + "</td></tr><tr><td>建议次数</td><td>" + data.adviceCount + "</td></tr><tr><td>风险分布</td><td>" + Object.keys(data.riskDistribution).map(function (k) { return k + "：" + data.riskDistribution[k]; }).join("，") + "</td></tr></table>") + "<p>数据来源：" + esc(data.source) + " · 生成时间：" + esc(data.generatedAt) + "</p><button onclick='window.print()'>打印 / 另存 PDF</button></body></html>";
    var w = root.open("", "qjzh-report", "width=900,height=700"); if (w) { w.document.write(html); w.document.close(); w.focus(); setTimeout(function () { try { w.print(); } catch (_) {} }, 120); return w; }
    var text = JSON.stringify(data, null, 2); if (root.navigator.clipboard) root.navigator.clipboard.writeText(text); else { var ta = root.document.createElement("textarea"); ta.value = text; root.document.body.appendChild(ta); ta.select(); root.document.execCommand("copy"); ta.remove(); } return null;
  }
  function renderInstitution(rows) { return render({ startDate: "", endDate: "", noRecords: !rows.length, complianceRate: rows.filter(function (r) { return Number(r.calibrated_nh3_ppm) < 10; }).length / (rows.length || 1), averageNh3: rows.reduce(function (s, r) { return s + Number(r.calibrated_nh3_ppm || 0); }, 0) / (rows.length || 1), maxNh3: rows.reduce(function (m, r) { return Math.max(m, Number(r.calibrated_nh3_ppm || 0)); }, 0), temperatureRange: { min: null, max: null }, adviceCount: rows.filter(function (r) { return Number(r.calibrated_nh3_ppm) >= 10; }).length, riskDistribution: {}, generatedAt: new Date().toISOString(), source: "机构模拟圈舍" }); }
  q.reportRenderer = { render: render, renderInstitution: renderInstitution };
  root.addEventListener("DOMContentLoaded", function () { root.document.getElementById("generateReport")?.addEventListener("click", function () { var d = q.reportGenerator.generate({ startDate: root.document.getElementById("reportStartDate")?.value, endDate: root.document.getElementById("reportEndDate")?.value }); var s = root.document.getElementById("reportStatus"); if (s) { s.className = "qjzh-data-state qjzh-state-" + (d.noRecords ? "warning" : "empty"); s.textContent = d.noRecords ? "所选范围内无记录" : "报告已生成，正在打开打印窗口。"; } render(d); }); });
})(window);
