"use strict";

const fs = require("node:fs");
const path = require("node:path");
const childProcess = require("node:child_process");

const ROOT = path.resolve(__dirname, "..");
const PUBLIC_FILES = Object.freeze([
  "index.html",
  "online_test.html",
  "404.html",
  "robots.txt",
  "sitemap.xml",
  "COPYRIGHT.md",
  "ORIGINALITY.md",
  "SECURITY.md",
  "originality-manifest.json",
  "docs",
  "dashboard.js",
  "riskPolicy.js",
  "model_weights.js",
  "compensator_engine.js",
  "knowledgeBase.js",
  "decisionEngine.js",
  "simulator.js",
  "ui_text_map.js",
  "errorHandler.js",
  "csvTemplate.js",
  "dataImport.js",
  "reportGenerator.js",
  "reportRenderer.js",
  "institutionView.js",
  "demoReset.js",
  "ui_interactions.js",
  "viewRouter.js",
  "knowledge-base-rules.md",
  "ALGORITHM_DOCUMENTATION.md",
  "assets"
]);

const PUBLIC_DOC_FILES = Object.freeze([
  "docs/USER_GUIDE.md",
  "docs/DATA_DICTIONARY.md",
  "docs/RELEASE_CHECKLIST.md"
]);

function argumentValue(name, fallback) {
  const index = process.argv.indexOf(name);
  return index >= 0 && process.argv[index + 1] ? process.argv[index + 1] : fallback;
}

function assertSafeOutput(output) {
  const parsed = path.parse(output);
  if (output === ROOT || output === parsed.root) {
    throw new Error("Refusing to replace unsafe output directory: " + output);
  }
}

function assertNoSymlinks(entry) {
  const stat = fs.lstatSync(entry);
  if (stat.isSymbolicLink()) throw new Error("Public artifact entries cannot be symbolic links: " + entry);
  if (!stat.isDirectory()) return;
  for (const child of fs.readdirSync(entry)) assertNoSymlinks(path.join(entry, child));
}

function resolveCommit() {
  const environmentCommit = String(process.env.GITHUB_SHA || "").trim();
  if (/^[0-9a-f]{40}$/i.test(environmentCommit)) return environmentCommit.toLowerCase();
  const repositoryCommit = childProcess.execFileSync("git", ["rev-parse", "HEAD"], {
    cwd: ROOT,
    encoding: "utf8",
    stdio: ["ignore", "pipe", "ignore"]
  }).trim();
  if (!/^[0-9a-f]{40}$/i.test(repositoryCommit)) throw new Error("Unable to determine a 40-character Git commit");
  return repositoryCommit.toLowerCase();
}

function resolveBuiltAt() {
  const requested = String(process.env.BUILD_TIMESTAMP || "").trim();
  if (requested) {
    const parsed = new Date(requested);
    if (!Number.isFinite(parsed.getTime())) throw new Error("BUILD_TIMESTAMP must be an ISO-8601 date");
    return parsed.toISOString();
  }
  return new Date().toISOString();
}

function metadataSource(commit, builtAt) {
  const runNumber = String(process.env.GITHUB_RUN_NUMBER || "").trim();
  const version = /^\d+$/.test(runNumber) ? "build-" + runNumber : "build-" + commit.slice(0, 12);
  return [
    "/* Generated by scripts/build-pages.js. Do not edit the deployed copy. */",
    "(function (root) {",
    "  \"use strict\";",
    "  root.BUILD_INFO = Object.freeze({",
    "    version: " + JSON.stringify(version) + ",",
    "    commit: " + JSON.stringify(commit) + ",",
    "    builtAt: " + JSON.stringify(builtAt) + ",",
    "    environment: \"production\"",
    "  });",
    "})(typeof window !== \"undefined\" ? window : globalThis);",
    ""
  ].join("\n");
}

function build() {
  const output = path.resolve(ROOT, argumentValue("--out", "dist"));
  assertSafeOutput(output);

  for (const entry of PUBLIC_FILES) {
    const source = path.join(ROOT, entry);
    if (!fs.existsSync(source)) throw new Error("Missing public artifact entry: " + entry);
    assertNoSymlinks(source);
  }
  for (const entry of PUBLIC_DOC_FILES) {
    const source = path.join(ROOT, entry);
    if (!fs.existsSync(source)) throw new Error("Missing public document: " + entry);
    assertNoSymlinks(source);
  }

  fs.rmSync(output, { recursive: true, force: true });
  fs.mkdirSync(output, { recursive: true });
  for (const entry of PUBLIC_FILES) {
    if (entry === "docs") continue;
    fs.cpSync(path.join(ROOT, entry), path.join(output, entry), { recursive: true, force: false });
  }
  fs.mkdirSync(path.join(output, "docs"), { recursive: true });
  for (const entry of PUBLIC_DOC_FILES) fs.cpSync(path.join(ROOT, entry), path.join(output, entry), { recursive: true, force: false });

  const commit = resolveCommit();
  const builtAt = resolveBuiltAt();
  fs.writeFileSync(path.join(output, "build_info.js"), metadataSource(commit, builtAt), "utf8");
  fs.writeFileSync(path.join(output, ".nojekyll"), "", "utf8");
  console.log("[pages-build] Published " + PUBLIC_FILES.length + " allowlisted entries to " + output);
  console.log("[pages-build] Commit " + commit + " · " + builtAt);
}

try {
  build();
} catch (error) {
  console.error("[pages-build] " + error.message);
  process.exit(1);
}
